### ISSUE TITLE
It's impossible to export a survey which contains a TagBox and Dynamic Panel with shared data

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#279] opened 2023-09-21 19:38 UTC
A problematic survey JSON is available in the user issue at 

T14731 - PDF creation fails: tag box and dependent dynamic panels
https://surveyjs.answerdesk.io/internal/ticket/details/T14731

Run a survey, click Yes, select some countries, and enter address data. Try to export a survey. No error in the console, no document is exported.

**Comment by andrewtelnov** [comment] 2023-09-24 12:03
The issue is fixed in [this issue](https://github.com/surveyjs/survey-library/issues/7001)

**Comment by andrewtelnov** [comment] 2023-09-25 09:24
The issue is fixed in [this PR](https://github.com/surveyjs/survey-library/pull/7002).

Thank you,
Andrew

**Closed by andrewtelnov** 2023-09-25 09:24 UTC
Labels: bug, user issue
