### ISSUE TITLE
Support asynchronous functions

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#277] opened 2023-09-21 07:59 UTC
User Issue: T14672 - How to execute a conditions for a survey model at later point of time in Survey PDF.
https://surveyjs.answerdesk.io/internal/ticket/details/T14672
***
In the meantime, a SurveyJS PDF Generator doesn't wait until a custom asynchronous function finishes executing.
[View Demo](https://codesandbox.io/s/surveyjs-angular-forked-3qyjp4?file=/src/app/components/pdf.component.ts)
Please support async functions in SurveyJS PDF Generator.

**Comment by andrewtelnov** [comment] 2023-09-24 12:04
The issue is fixed in [this issue](https://github.com/surveyjs/survey-library/issues/7001)

**Closed** 2023-09-25 09:27 UTC
Labels: enhancement, user issue
